version: 'version: "3.7"'

# networks
networks:
  my-network:
    driver: bridge

# services
services:
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - my-network
    restart: always

  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    networks:
      - my-network
    environment:
      - NODE_ENV=production
    restart: always

  nginx: 
    container_name: nginx
    image: nginx:1.23.3-alpine
    restart: always
    networks:
      - my-network
    volumes:
      - ./server/.nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - server
