const images = {
    logo: require('~/assets/images/logo.svg').default,
    home_icon_thin: require('~/assets/images/home-icon-thin.svg').default,
    search_icon_thin: require('~/assets/images/search-icon-thin.svg').default,
    compass_icon_thin: require('~/assets/images/compass-icon-thin.svg').default,
    video_icon_thin: require('~/assets/images/video-icon-thin.svg').default,
    message_icon_thin: require('~/assets/images/message-icon-thin.svg').default,
    notify_icon_thin: require('~/assets/images/notify-icon-thin.svg').default,
    create_icon_thin: require('~/assets/images/create-icon-thin.svg').default,
    menu_icon_thin: require('~/assets/images/menu-icon-thin.svg').default,
    home_icon_solid: require('~/assets/images/home-icon-solid.svg').default,
    search_icon_solid: require('~/assets/images/search-icon-solid.svg').default,
    compass_icon_solid: require('~/assets/images/compass-icon-solid.svg').default,
    video_icon_solid: require('~/assets/images/video-icon-solid.svg').default,
    message_icon_solid: require('~/assets/images/message-icon-solid.svg').default,
    notify_icon_solid: require('~/assets/images/notify-icon-solid.svg').default,
    create_icon_solid: require('~/assets/images/create-icon-solid.svg').default,
    menu_icon_solid: require('~/assets/images/menu-icon-solid.svg').default,
    setting_icon: require('~/assets/images/setting-icon.svg').default,
    activity_icon: require('~/assets/images/activity-icon.svg').default,
    mode_icon: require('~/assets/images/mode-icon.svg').default,
    saved_icon: require('~/assets/images/saved-icon.svg').default,
    problem_icon: require('~/assets/images/problem-icon.svg').default,
    logo_icon: require('~/assets/images/logo-icon.svg').default,
    close_icon_bg: require('~/assets/images/close-icon-bg.svg').default,
    check_bg: require('~/assets/images/check-bg.png'),
    microsoft: require('~/assets/images/microsoft.png'),
    chPlay: require('~/assets/images/chplay.png'),
    home_phones: require('~/assets/images/home-phones-1.png'),
    screenshot1: require('~/assets/images/screenshot1.png'),
    screenshot2: require('~/assets/images/screenshot2.png'),
    screenshot3: require('~/assets/images/screenshot3.png'),
    screenshot4: require('~/assets/images/screenshot4.png'),
    logoLoader: require('~/assets/images/logo.png'),
    synthetic: require('~/assets/images/synthetic.png'),
    notAvatar: require('~/assets/images/not-avatar.png'),
    filers: {
        normal: require('~/assets/images/normal.jpg'),
        aden: require('~/assets/images/aden.jpg'),
        clarendon: require('~/assets/images/clarendon.jpg'),
        crema: require('~/assets/images/crema.jpg'),
        moon: require('~/assets/images/moon.jpg'),
        slumber: require('~/assets/images/slumber.jpg'),
    },
    sharePosts: require('~/assets/images/share-posts.gif'),
    notSharePosts: require('~/assets/images/not-share-posts.svg').default,
};

export default images;
